title: Akshay's Website
description: I like to design systems, write code and host people in Himalayas.

url: https://amyglan.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/
header: small
# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
social:
    github: amyglan
    twitter: pahadomay
    facebook: brianmaierjr
    email: akshaygupta22497@gmail.com
    linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: akshay
